# Generated by Django 3.1.3 on 2023-04-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20230401_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='company',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
