# Generated by Django 3.1.3 on 2023-04-01 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20230401_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter',
            name='company',
        ),
    ]
