# Generated by Django 3.1.3 on 2023-04-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_remove_recruiter_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='company',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
