# Generated by Django 3.1.3 on 2023-04-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='vacancy',
            field=models.FloatField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
