# Generated by Django 3.1.3 on 2023-04-01 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_job_vacancy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='vacancy',
        ),
    ]
